name: API
on:
  push:
    branches: [api]

jobs:

  test-pull-request:
    name: Test Pull Request to dev
    runs-on: ubuntu-latest
    env:
      DB_NAME: test
      DB_USER: dev1
      DB_PASS: pass1
    steps:
      - name: Checkout API Branch
        uses: actions/checkout@v2
        with:
          ref: 'api'

      - name: Setup PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_NAME }}"
          sudo -u postgres psql -c "CREATE USER ${{ env.DB_USER }} WITH ENCRYPTED PASSWORD '${{ env.DB_PASS }}'"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ env.DB_NAME }} TO ${{ env.DB_USER }}"          

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Run Unit + Integration Tests
        working-directory: ./api
        run: 'mvn clean install'

      - name: Create Pull Request to dev
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev"
          pr_title: "Pulling ${{ github.ref }} to branch 'dev'"
          pr_body: "👑 *An automated PR*"
          github_token: ${{ secrets.GITHUB_TOKEN }}


      # - name: Cancel workflow on failure
      #   if: failure()
      #   uses: andymckay/cancel-action@0.2

      - name: Cancel workflow on failure
        if: failure()
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Fail workflow on failure')

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build
        working-directory: ./frontend
        run: yarn install && yarn format && yarn lint && yarn build
      - name: Run Unit Tests
        working-directory: ./frontend
        run: yarn test:unit
      - name: Run Integration Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          wait-on-timeout: 30
          browser: chrome
          headless: true
      - name: Cancel workflow on failure
        if: failure()
        uses: andymckay/cancel-action@0.2