name: API
on:
  push:
    branches: [api]
    
jobs:
      
  api:
    name: API Build + Tests 
    runs-on: ubuntu-latest
    env:
      DB_NAME: test
      DB_USER: dev1
      DB_PASS: pass1
    outputs:
      pr-number: ${{ steps.create-pr.outputs.pr_number }} 
    steps:
      - name: Checkout API Branch
        uses: actions/checkout@v2
        with:
          ref: 'api'

      - name: Setup PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE ${{ env.DB_NAME }}"
          sudo -u postgres psql -c "CREATE USER ${{ env.DB_USER }} WITH ENCRYPTED PASSWORD '${{ env.DB_PASS }}'"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ env.DB_NAME }} TO ${{ env.DB_USER }}"          

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Run Unit + Integration Tests
        working-directory: ./api
        run: 'mvn clean install'

      - name: pull-request
        uses: repo-sync/pull-request@v2
        id: create-pr
        with:
          destination_branch: "dev"                      
          pr_title: "Pulling ${{ github.ref }} into dev"
          pr_body: ":crown: *An automated PR*"       
          pr_label: "automerge"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    name: Automerge PR 
    runs-on: ubuntu-latest
    needs: [api]
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: ${{ needs.api.outputs.pr-number }} 
