# run ci/cd on push at dev -> merge to master if passed
# todo: run ci/cd (with prod env) on push at master

name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:

  backend_dev:
    if: github.ref == 'refs/heads/dev'
    name: DEV_Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup backend
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Run tests
        working-directory: ./api
        run: mvn clean install

  frontend_dev:
    if: github.ref == 'refs/heads/dev'
    name: DEV_Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: install yarn
        run: npm install -g yarn

      - name: setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock

      - name: Frontend build
        working-directory: ./frontend
        run: |
          yarn install
          yarn lint
          yarn build
