# on push "dev": build, unit, integration, local e2e tests -> PASSED -> merge to "staging"
# on push "staging": design, performance, live e2e tests -> PASSED -> wait for approval
# on "approved": merge "staging" to "master" -> deploy 

name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:

  backend_dev:
    if: github.ref == 'refs/heads/dev'
    name: Backend Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup backend
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Run tests
        working-directory: ./api
        run: mvn clean install

  frontend_dev:
    if: github.ref == 'refs/heads/dev'
    name: Frontend Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: install yarn
        run: npm install -g yarn

      - name: setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock

      - name: build
        working-directory: ./frontend
        run: |
          yarn install
          yarn build
      
      - name: lint
        working-directory: ./frontend
        run: |
          yarn format
          yarn lint

      - name: unit test
        working-directory: ./frontend
        run: yarn test:unit

      - name: integration test
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          wait-on-timeout: 30
          browser: chrome
          headless: true

