name: automerge
on:
  pull_request:
    branches: [dev]
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
concurrency:
  group: dev
  cancel-in-progress: true
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: TRIGGERED REF
        run: echo ref = ${{ github.ref }}
      - name: BASE REF
        run: echo base ref = ${{ github.base_ref }}
      - name: HEAD REF
        run: echo base ref = ${{ github.head_ref }}
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # MERGE_COMMIT_MESSAGE: pull-request-title
          # try every 5 sec (default) for 5 mins
          MERGE_RETRIES: 60