name: Dev

on:
  workflow_run:
    workflows: ["API"]
    types: [completed]

jobs:
  api-frontend-integration:
    name: API + Frontend Integration
    runs-on: ubuntu-latest
    steps:

      - name: Echo on merged
        run: 'SUCCESS!'