name: Dev

on:
  pull_request:
    branches: [dev, api]
    types: [closed]

jobs:
  api-frontend-integration:
    if: github.event.pull_request.merged == true
    name: API + Frontend Integration
    runs-on: ubuntu-latest
    steps:
      - name: Echo on merged
        run: 'MERGED!'