name: Dev

on:
  workflow_run:
    workflows: [API]
    types: [completed]

jobs:
  api-frontend-integration:
    name: API + Frontend Integration
    runs-on: ubuntu-latest
    steps:

      - name: echo somethign
        run: echo ${{ github.event.workflow_run.conclusion }}

      - name: Echo on merged
        if: github.event.workflow_run.conclusion == 'success'
        run: 'SUCCESS!'