name: Dev 
on:
  push:
  workflow_dispatch:
  pull_request:
    
jobs:
  e2e_test:
    name: End-to-end Tests
    if: github.ref == 'refs/heads/dev.api'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test   
          POSTGRES_USER: dev1     
          POSTGRES_PASSWORD: pass1
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: clone dev branch
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: build api
        working-directory: ./api
        # skip unit & integration tests (this should be done on previous workflow)
        run: mvn clean install -DskipTests

      - name: install 
        run: npm install -g yarn

      - name: setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock
      
      - name: build frontend
        working-directory: ./frontend
        run: |
          yarn install
          yarn build

      - name: 'TODO'
        run: echo "TODO e2e tests"

      