name: Frontend
on:
  push:
    branches: [frontend]
    
jobs:
  
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: frontend/yarn.lock
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build
        working-directory: ./frontend
        run: yarn install && yarn format && yarn lint && yarn build
      - name: Run Unit Tests
        working-directory: ./frontend
        run: yarn test:unit
      - name: Run Integration Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          wait-on-timeout: 30
          browser: chrome
          headless: true
      - name: Cancel workflow on failure
        if: failure()
        uses: andymckay/cancel-action@0.2

  merge-to-dev:
    name: Merge to dev branch
    runs-on: ubuntu-latest
    needs: [frontend]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Merge
        run: |
          git checkout dev
          git merge frontend --commit -m 'merge frontend -> dev'
          git push origin dev