name: Staging

on:
  push:
    branches: [staging]

jobs:

  deploy:
    name: Merge dev -> staging
    runs-on: ubuntu-latest
    steps:
      - name: "TODO: Deploy"
        run: echo "deploy to vercel, heroku"

      - name: Create pull request staging -> master
        uses: repo-sync/pull-request@v2
        id: create-pr
        with:
          destination_branch: "master"                      
          pr_title: "Pulling ${{ github.ref }} into dev"
          pr_body: ":crown: *An automated PR*"       
          pr_label: "automerge"
          github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: 'TODO: if accept, merge to master, then deploy to production'
        run: echo "..."
